# Generated by Django 5.2 on 2025-12-11 22:55

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torchecker', '0002_alter_tortransferee_co_requisite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(db_index=True, help_text='Student account identifier', max_length=100, validators=[core.validators.validate_account_id])),
                ('file', models.ImageField(help_text='Uploaded TOR image', upload_to='tor_documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'TOR Document',
                'verbose_name_plural': 'TOR Documents',
                'db_table': 'tor_document',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['account_id'], name='tor_documen_account_a59f5b_idx'), models.Index(fields=['uploaded_at'], name='tor_documen_uploade_95e2c7_idx')],
            },
        ),
    ]